I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 28, in script
    aly "Что, если я не найду любимую работу? "
Exception: Sayer 'aly' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 28, in script
    aly "Что, если я не найду любимую работу? "
  File "C:\Users\mouse\Desktop\renpy-8.3.2-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "C:\Users\mouse\Desktop\renpy-8.3.2-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\mouse\Desktop\renpy-8.3.2-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'aly' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.3.24101701+nightly
VisualNovel 1.0
Fri Oct 18 21:48:18 2024
